improve ndk download

diff --git a/prepareDevelopment b/prepareDevelopment
--- a/prepareDevelopment
+++ b/prepareDevelopment
@@ -7,8 +7,14 @@ popd
 export MIRAI_ROOT_PATH="$SCRIPT_ROOT"
 export MIRAI_PROJECTS_PATH="$MIRAI_ROOT_PATH/Projects"
 export MIRAI_PRODUCTS_ANDROID_PATH="$MIRAI_ROOT_PATH/Products/android"
-export ANDROID_NDK_PATH="$MIRAI_PRODUCTS_ANDROID_PATH/android-ndk-r9" # if you already has NDK, change this to you NDK path
+
+if [ "$ANDROID_NDK_PATH" == "" ]; then
+export ANDROID_NDK_PATH="$MIRAI_PRODUCTS_ANDROID_PATH/android-ndk-r9b" # if you already has NDK, change this to you NDK path
+fi
+if [ "$ANDROID_JDK_PATH" == "" ]; then
 export ANDROID_JDK_PATH="$MIRAI_PRODUCTS_ANDROID_PATH/android-jdk" # if you already has JDK, change this to you JDK path
+fi
+
 export STANDALONE_TOOLCHAIN_PATH="$MIRAI_PRODUCTS_ANDROID_PATH/android-toolchain-arm"
 export GNUSTEP_MAKE_CONFIG_PATH="$MIRAI_PROJECTS_PATH/dependencies/config"
 export SYSROOTFLAGS_ARM="--sysroot $STANDALONE_TOOLCHAIN_PATH/sysroot"
@@ -49,6 +55,7 @@ buildGNUstepMake()
 	pushd $MIRAI_PROJECTS_PATH/dependencies
 
     if [ ! -f gnustep-make-2.6.2.tar.gz ]; then
+		echo "Downloadng gnustep-make-2.6.2..."
         curl ftp://ftp.gnustep.org/pub/gnustep/core/gnustep-make-2.6.2.tar.gz > gnustep-make-2.6.2.tar.gz
     fi
     tar -xzf gnustep-make-2.6.2.tar.gz
@@ -75,6 +82,7 @@ prepareConfig()
 	pushd $MIRAI_PROJECTS_PATH/dependencies
 
 	if [ ! -d config ]; then
+		echo "Downloadng gnustep's config..."
 	    git clone http://git.savannah.gnu.org/r/config.git/ config
 	fi
 	popd
@@ -85,8 +93,14 @@ prepareConfig()
 if [ ! -d $ANDROID_NDK_PATH ]; then
 	pushd $MIRAI_PRODUCTS_ANDROID_PATH
 	
-	curl http://dl.google.com/android/ndk/android-ndk-r9b-darwin-x86_64.tar.bz2 -o android-ndk-r9b-darwin-x86_64.tar.bz2
-	tar -xvz android-ndk-r9b-darwin-x86_64.tar.bz2
+	echo "Missing Android NDK, will download it, if you already has NDK, please set it to environment: ANDROID_NDK_PATH"
+	echo "Downloadng Android NDK..."
+	
+	if [ ! -f android-ndk-r9b-darwin-x86_64.tar.bz2 ]; then
+		curl http://dl.google.com/android/ndk/android-ndk-r9b-darwin-x86_64.tar.bz2 -o android-ndk-r9b-darwin-x86_64.tar.bz2
+	fi
+	
+	tar -xvyf android-ndk-r9b-darwin-x86_64.tar.bz2
 	
 	if [ -d $ANDROID_NDK_PATH ]; then
 		rm android-ndk-r9b-darwin-x86_64.tar.bz2
@@ -98,10 +112,15 @@ fi
 if [ ! -d $ANDROID_JDK_PATH ]; then
 	pushd $MIRAI_PRODUCTS_ANDROID_PATH
 	
+	echo "Missing Android SDK, will download it, if you already has Android SDK, please set it to environment: ANDROID_JDK_PATH"
+	echo "Downloadng Android SDK adt-bundle-mac-x86_64-20131030.zip..."
 	curl http://dl.google.com/android/adt/adt-bundle-mac-x86_64-20131030.zip -o adt-bundle-mac-x86_64-20131030.zip
-	tar -vxz adt-bundle-mac-x86_64-20131030.zip
+	tar -vxzf adt-bundle-mac-x86_64-20131030.zip
 	if [ -d $ANDROID_JDK_PATH ]; then
 		rm android-ndk-r9b-darwin-x86_64.tar.bz2
+	else
+		echo "Missing Android SDK folder, take a look what's extracted folder name"
+		exit 1;
 	fi
 	
 	popd
