improve script

diff --git a/Projects/runtime/objc/buildObjC2 b/Projects/runtime/objc/buildObjC2
--- a/Projects/runtime/objc/buildObjC2
+++ b/Projects/runtime/objc/buildObjC2
@@ -4,6 +4,13 @@ pushd `pwd`/`dirname $0`
 SCRIPT_ROOT=`pwd`
 popd
 
+checkError()
+{
+    if [ "${1}" -ne "0" ]; then
+        echo "*** Error: ${2}"
+        exit ${1}
+    fi
+}
 
 # TODO: before build libobjc2, needs build libdispatch
 if [ ! -f $STANDALONE_TOOLCHAIN_PATH/sysroot/usr/lib/libobjc.so ]; then
@@ -27,8 +34,11 @@ if [ ! -f $STANDALONE_TOOLCHAIN_PATH/sysroot/usr/lib/libobjc.so ]; then
 	# disable test, some tests failed due to cross-compiled 
 	cmake -DTESTS=0 -DCMAKE_TOOLCHAIN_FILE=$SCRIPT_ROOT/../../toolchain.cmake -DCMAKE_FIND_ROOT_PATH=$STANDALONE_TOOLCHAIN_PATH/sysroot -DCMAKE_INSTALL_PREFIX=/usr ..
 	make
-	make install 
-	#DESTDIR=$STANDALONE_TOOLCHAIN_PATH/sysroot
+	checkError $? "build objc2 failed"
+	
+	make install DESTDIR=$STANDALONE_TOOLCHAIN_PATH/sysroot
+	checkError $? "make install objc2 failed"
+	
 	popd
 
 fi
